<a href="https://colab.research.google.com/github/Bigdata92/190902AdvancedVisualPerception/blob/master/190904VisualPerception01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
a.dtype

dtype('int64')

In [4]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

###  a = np.array(1,2,3,4) 오류 
###  b = np.array([1,2,3,4]) Good

In [6]:
b= np.array([(1.5,2,3), (4,5,6)])
            
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
c = np.array([[1,2,], [3,4]], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones([2,3,4], dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
np.empty([2,3])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [13]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [14]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [16]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
x = np.linspace(0, 2*pi, 100)

In [19]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [20]:
np.array([1,2,3]) 

array([1, 2, 3])

In [21]:
np.array([1,2,3.0]) # upcasting

array([1., 2., 3.])

In [22]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [24]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])

In [26]:
x = np.arange(6)
x = x.reshape([2,3])
x

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
y = np.arange(3, dtype = float)
y

array([0., 1., 2.])

In [29]:
np.zeros_like(y)

array([0., 0., 0.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones([5,], dtype = int)

array([1, 1, 1, 1, 1])

In [35]:
np.ones([2,1])

array([[1.],
       [1.]])

In [33]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

### empty 사용안함

In [36]:
np.arange(3)

array([0, 1, 2])

In [38]:
np.arange(3.0)

array([0., 1., 2.])

In [39]:
np.arange(3,7)

array([3, 4, 5, 6])

In [40]:
np.arange(3,7)

array([3, 4, 5, 6])

In [41]:
np.random.rand(3,2)

array([[0.96565024, 0.17036652],
       [0.033082  , 0.83984903],
       [0.37558203, 0.9160717 ]])

In [42]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [43]:
c = a-b
c

array([20, 29, 38, 47])

In [45]:
b**2

array([0, 1, 4, 9])

In [46]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[0,4]])
A*B

array([[2, 0],
       [0, 4]])

In [47]:
A@B #내적방법1

array([[2, 4],
       [0, 4]])

In [48]:
A.dot(B) #내적방법2

array([[2, 4],
       [0, 4]])

In [49]:
a = np.ones((2,3), dtype = int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [50]:
b += a
b

array([[3.23773038, 3.96549839, 3.42924018],
       [3.55387475, 3.92071777, 3.07627352]])

In [0]:
# 에러 a += b 
# '케라스 창시자에게 배우는 딥러닝' 추천

In [54]:
a = np.random.random((2,3))
a

array([[0.48532078, 0.86419265, 0.92648428],
       [0.00440507, 0.97854814, 0.7247263 ]])

In [55]:
a.sum()

3.9836772230513118

In [56]:
a.min()

0.004405069979887877

In [57]:
a.max()

0.978548142013583

In [58]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [60]:
b.min(axis = 1)

array([0, 4, 8])

In [61]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [63]:
B = np.arange(3)
B

array([0, 1, 2])

In [64]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [65]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [0]:
C = np.array([2, -1, 4])

In [67]:
np.add(B, C)

array([2, 0, 6])

In [68]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [69]:
np.argmax(a) #augument(원소)의 max 위치

5

In [70]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [71]:
np.argmax(a, axis=1)

array([2, 2])

In [0]:
a = np.array([-1.7, -1,5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [73]:
np.ceil(a)

array([-1., -1.,  5., -0.,  1.,  2.,  2.,  2.])

In [75]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [76]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.clip(a, 3, 6, out=a)

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [79]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.clip(a, [3,4,1,1,1,4,4,4,4,4],8)

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

In [81]:
a = np.array([-1.7, 1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2.,  1., -1.,  0.,  1.,  1.,  2.])

In [83]:
a = np.array([[1,2],[3,4]])
np.mean(a)

2.5

In [84]:
np.mean(a, axis=0)

array([2., 3.])

In [85]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [86]:
a = np.array([[10,7,4],[3,2,1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [87]:
np.median(a) #중간값

3.5

In [88]:
np.median(a, axis=0)

array([6.5, 4.5, 2.5])

In [89]:
np.median(a, axis=1)

array([7., 2.])

In [90]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.where(a<5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [92]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
np.concatenate((a, b.T), axis=1) #이 함수보다 pandas concat() 사용

array([[1, 2, 5],
       [3, 4, 6]])

In [95]:
np.concatenate((a,b), axis=None) # concatenate - 이어붙인다

array([1, 2, 3, 4, 5, 6])

In [96]:
  np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
x = np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [99]:
np.squeeze(x).shape #squeeze 많이 사용

(3,)

In [100]:
  np.squeeze(x, axis=0).shape

(3, 1)

In [0]:
#np.squeeze(x, axis=1).shape - 에러뜸

In [102]:
np.squeeze(x, axis=2).shape

(1, 3)